var React = require('react');
var game_1 = require('./game');
class GameList extends React.Component {
    constructor(props) {
        super(props);
    }
    render() {
        var gameNodes = this.props.games.map(function (game) {
            return (React.createElement(game_1.default, {"game": game}));
        });
        return (React.createElement("div", {"className": "card blue-grey darken-1"}, React.createElement("div", {"className": "card-content white-text"}, React.createElement("span", {"className": "card-title"}, "Games played"), React.createElement("div", {"className": "row"}, React.createElement("div", {"className": "col s2"}, React.createElement("input", {"id": "date", "type": "text", "className": "validate"}), React.createElement("label", {"htmlFor": "date"}, "Date")), React.createElement("div", {"className": "col s2"}, React.createElement("input", {"id": "challenger", "type": "text", "className": "validate"}), React.createElement("label", {"htmlFor": "challenger"}, "Challenger")), React.createElement("div", {"className": "col s2"}, React.createElement("input", {"id": "defender", "type": "text", "className": "validate"}), React.createElement("label", {"htmlFor": "defender"}, "Defender")), React.createElement("div", {"className": "col s2"}, React.createElement("input", {"id": "defender_points", "type": "text", "className": "validate"}), React.createElement("label", {"htmlFor": "defender_points"}, "Defender points")), React.createElement("div", {"className": "col s2"}, React.createElement("input", {"id": "challenger_points", "type": "text", "className": "validate"}), React.createElement("label", {"htmlFor": "challenger_points"}, "Challenger points")), React.createElement("div", {"className": "col s1  "}, React.createElement("input", {"id": "game_type", "type": "text", "className": "validate"}), React.createElement("label", {"htmlFor": "game_type"}, "Game type"))), React.createElement("table", null, React.createElement("thead", null, React.createElement("tr", null, React.createElement("th", {"data-field": "id"}, "Id"), React.createElement("th", {"data-field": "date"}, "Game date"), React.createElement("th", {"data-field": "challenger"}, "Challenger"), React.createElement("th", {"data-field": "defender"}, "Defender"), React.createElement("th", {"data-field": "challengerPoints"}, "Challenger points"), React.createElement("th", {"data-field": "defenderPoints"}, "Defender points"), React.createElement("th", {"data-field": "gameType"}, "Game type"), React.createElement("th", {"data-field": "winner"}, "Winner"))), React.createElement("tbody", null, gameNodes))), React.createElement("div", {"className": "card-action"}, React.createElement("a", {"href": "#"}, "This is a link"))));
    }
}
exports.default = GameList;
//# sourceMappingURL=gamelist.js.map